name: citrus_planer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Light.ttf
          weight: 300
        - asset: assets/fonts/RobotoMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight: 700